Models/ApplicationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace GetHair_Egypt.Models
{
    public class ApplicationsController : Controller
    {
        private GHEEntities db = new GHEEntities();

        // GET: Applications
        public ActionResult Index()
        {
            var applications = db.Applications.Include(a => a.Client).Include(a => a.Clinic);
            return View(applications.ToList());
        }

        // GET: Applications/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Application application = db.Applications.Find(id);
            if (application == null)
            {
                return HttpNotFound();
            }
            return View(application);
        }

        // GET: Applications/Create
        public ActionResult Create(int? id)
        {
            if (Session["userName"] != null)
            {
                ViewBag.UserID = Session["ID"];
                ViewBag.CID = id;
                Clinic clinic = db.Clinics.Find(id);
                ViewBag.CImage1 = clinic.CImage1;
                ViewBag.CImage2 = clinic.CImage2;
                ViewBag.CImage3 = clinic.CImage3;
                ViewBag.CImage4 = clinic.CImage4;
                ViewBag.Address = clinic.Address;
                ViewBag.Description = clinic.Description;

                return View();
            }
            else return RedirectToAction("Login", "Clients");

        }

        // POST: Applications/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "AppID,UserID,CID,AppDate")] Application application)
        {
            if (ModelState.IsValid)
            {
              
                db.Applications.Add(application);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.UserID = Session["ID"];
            ViewBag.CID = new SelectList(db.Clinics, "CID", "CName", application.CID);
            return View(application);
        }

        // GET: Applications/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Application application = db.Applications.Find(id);
            if (application == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserID = new SelectList(db.Clients, "UserID", "FName", application.UserID);
            ViewBag.CID = new SelectList(db.Clinics, "CID", "CName", application.CID);
            return View(application);
        }

        // POST: Applications/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "AppID,UserID,CID,AppDate")] Application application)
        {
            if (ModelState.IsValid)
            {
                db.Entry(application).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UserID = new SelectList(db.Clients, "UserID", "FName", application.UserID);
            ViewBag.CID = new SelectList(db.Clinics, "CID", "CName", application.CID);
            return View(application);
        }

        // GET: Applications/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Application application = db.Applications.Find(id);
            if (application == null)
            {
                return HttpNotFound();
            }
            return View(application);
        }

        // POST: Applications/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Application application = db.Applications.Find(id);
            db.Applications.Remove(application);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Models/Clinic.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetHair_Egypt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clinic
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clinic()
        {
            this.Applications = new HashSet<Application>();
        }
    
        public string CName { get; set; }
        public string Email { get; set; }
        public string CUrl { get; set; }
        public string Password { get; set; }
        public string CImage1 { get; set; }
        public string CImage2 { get; set; }
        public string CImage3 { get; set; }
        public string CImage4 { get; set; }
        public int CID { get; set; }
        public string Address { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Application> Applications { get; set; }
    }
}

Controllers/ClinicsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GetHair_Egypt.Models;
using System.IO;

namespace GetHair_Egypt.Controllers
{
    public class ClinicsController : Controller
    {
        private GHEEntities db = new GHEEntities();

        // GET: Clinics
        public ActionResult Index()
        {
            if (Session["userName"] != null)
                return View(db.Clinics.ToList());
           else
                return RedirectToAction("Login"); 
          //Uncomment apove for security
        }

        // GET: Clinics/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Clinic clinic = db.Clinics.Find(id);
            if (clinic == null)
            {
                return HttpNotFound();
            }
            return View(clinic);
        }

        // GET: Clinics/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Clinics/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CName,Email,CUrl,Password,Address, Description")] Clinic clinic, HttpPostedFileBase imgFile1, HttpPostedFileBase imgFile2, HttpPostedFileBase imgFile3, HttpPostedFileBase imgFile4)
        {
            if (ModelState.IsValid)
            {
                string path1 = "";
                string path2 = "";
                string path3 = "";
                string path4 = "";

               try {

                if (imgFile1 != null)
                {
                    path1 = "~/Images/" + Path.GetFileName(imgFile1.FileName);

                    imgFile1.SaveAs(Server.MapPath(path1));
                }

                if (imgFile2 != null)
                {
                    path2 = "~/Images/" + Path.GetFileName(imgFile2.FileName);

                    imgFile2.SaveAs(Server.MapPath(path2));
                }

                if (imgFile3 != null)
                {
                    path3 = "~/Images/" + Path.GetFileName(imgFile3.FileName);

                    imgFile3.SaveAs(Server.MapPath(path3));
                }

                if (imgFile4 != null)
                {
                    path4 = "~/Images/" + Path.GetFileName(imgFile4.FileName);

                    imgFile4.SaveAs(Server.MapPath(path4));
                }
            }
            catch (Exception)
               {
                ViewBag.FileStatus = "Error while image uploading."; ;
               }

                clinic.CImage1 = path1;
                clinic.CImage2 = path2;
                clinic.CImage3 = path3;
                clinic.CImage4 = path4;

                db.Clinics.Add(clinic);
                db.SaveChanges();
                return RedirectToAction("");
            }

            return View(clinic);
        }

        // GET: Clinics/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Clinic clinic = db.Clinics.Find(id);
            if (clinic == null)
            {
                return HttpNotFound();
            }
            return View(clinic);
        }

        // POST: Clinics/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit( Clinic clinic, HttpPostedFileBase imgFile1, HttpPostedFileBase imgFile2, HttpPostedFileBase imgFile3, HttpPostedFileBase imgFile4)
        {
            if (ModelState.IsValid)
            {
                string path1 = "";
                string path2 = "";
                string path3 = "";
                string path4 = "";

                try
                {

                    if (imgFile1 != null)
                    {
                        path1 = "~/Images/" + Path.GetFileName(imgFile1.FileName);

                        imgFile1.SaveAs(Server.MapPath(path1));
                    }

                    if (imgFile2 != null)
                    {
                        path2 = "~/Images/" + Path.GetFileName(imgFile2.FileName);

                        imgFile2.SaveAs(Server.MapPath(path2));
                    }

                    if (imgFile3 != null)
                    {
                        path3 = "~/Images/" + Path.GetFileName(imgFile3.FileName);

                        imgFile3.SaveAs(Server.MapPath(path3));
                    }

                    if (imgFile4 != null)
                    {
                        path4 = "~/Images/" + Path.GetFileName(imgFile4.FileName);

                        imgFile4.SaveAs(Server.MapPath(path4));
                    }
                }
                catch (Exception)
                {
                    ViewBag.FileStatus = "Error while image uploading."; ;
                }

                clinic.CImage1 = path1;
                clinic.CImage2 = path2;
                clinic.CImage3 = path3;
                clinic.CImage4 = path4;
               var before = db.Clinics.AsNoTracking().Where(x => x.CID == clinic.CID).ToList().FirstOrDefault();
                clinic.Password = before.Password;
                clinic.confEmail = before.confEmail;
                clinic.confPassword = before.confPassword;
                db.Entry(clinic).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(clinic);
        }

        // GET: Clinics/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Clinic clinic = db.Clinics.Find(id);
            if (clinic == null)
            {
                return HttpNotFound();
            }
            return View(clinic);
        }

        // POST: Clinics/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Clinic clinic = db.Clinics.Find(id);
            db.Clinics.Remove(clinic);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult Login()
        {
            Session["userName"] = null;

            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login([Bind(Include ="Email,Password")]Clinic clinic)
        {
            var rec = db.Clinics.Where(x => x.Email == clinic.Email && x.Password == clinic.Password).FirstOrDefault();
            if (rec != null)
            {
                Session["userName"] = rec.CName; 
                return RedirectToAction("Index");
            }
            else
            {
                ViewBag.error = "Invalid Email or Password";
                return View(clinic);
            }
        }

        public ActionResult HomePage()
        {
            var recs = db.Clinics.ToList();
            if (Session["userName"] != null)
                return View(recs);
            else return RedirectToAction("Login", "Clients");


        }
    }
}

Views/Clinics/Create.cshtml
@model GetHair_Egypt.Models.Clinic

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Clinics", FormMethod.Post, new { enctype="multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Clinic</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.CName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.confEmail, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.confEmail, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.confEmail, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.CUrl, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CUrl, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CUrl, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.PasswordFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.confPassword, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.PasswordFor(model => model.confPassword, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.confPassword, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.CImage1, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @*   @Html.EditorFor(model => model.CImage1, new { htmlAttributes = new { @class = "form-control" } }) *@
            <input type="file" id="imgFile1" name="imgFile1" class="form-control" />
            @Html.ValidationMessageFor(model => model.CImage1, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CImage2, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" id="imgFile2" name="imgFile2" class="form-control" />
            @Html.ValidationMessageFor(model => model.CImage2, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CImage3, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" id="imgFile3" name="imgFile3" class="form-control" />
            @Html.ValidationMessageFor(model => model.CImage3, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CImage4, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" id="imgFile4" name="imgFile4" class="form-control" />
            @Html.ValidationMessageFor(model => model.CImage4, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Clinics/Delete.cshtml
@model GetHair_Egypt.Models.Clinic

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Clinic</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CUrl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CUrl)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CImage1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CImage1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CImage2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CImage2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CImage3)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CImage3)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CImage4)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CImage4)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/Clinics/Details.cshtml
@model GetHair_Egypt.Models.Clinic

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Clinic</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CUrl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CUrl)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CImage1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CImage1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CImage2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CImage2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CImage3)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CImage3)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CImage4)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CImage4)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.CName }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Clinics/Edit.cshtml
@model GetHair_Egypt.Models.Clinic

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Clinics",FormMethod.Post, new {enctype ="multipart/form-data"  }))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Clinic</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.CName)

    <div class="form-group">
        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CUrl, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CUrl, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CUrl, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CImage1, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" id=" = imgFile1" class="form-control" />
            @Html.ValidationMessageFor(model => model.CImage1, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CImage2, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" id=" = imgFile2" class="form-control"/>
            @Html.ValidationMessageFor(model => model.CImage2, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CImage3, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" id=" = imgFile3" class="form-control" />
            @Html.ValidationMessageFor(model => model.CImage3, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CImage4, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" id=" = imgFile4" class="form-control" />
            @Html.ValidationMessageFor(model => model.CImage4, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Clinics/HomePage.cshtml
@model IEnumerable<GetHair_Egypt.Models.Clinic>

@{
    ViewBag.Title = "HomePage";
}

<h2>Clinics</h2>
<h2>@Session["ID"]</h2>

<div class="row">

    @foreach (var item in Model)
    {
        <div class="col-sm-6 col-md-4">
            <div class="thumbnail">
                <img src="@Url.Content(item.CImage1)" alt="..." width="242" height="200">
                <div class="caption">
                    <h3>@item.CName</h3>
                    <p>...</p>
                    <p><a> @Html.ActionLink("Apply", "Create","Applications", new { id = item.CID }, new { @class = "btn btn-primary" }) </a> </p>
                </div>
            </div>
        </div>
    }
</div>

@* @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")

    <script type="text/javascript">
        $('.btn-primary').click(function () {
            document.location = '@Url.Action("Create","Applications")';
        });

    </script> *@
}

Views/Clinics/Index.cshtml
@model IEnumerable<GetHair_Egypt.Models.Clinic>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model. Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CUrl)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CImage1)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CImage2)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CImage3)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CImage4)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.Email)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.CUrl)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Address)
    </td>
    <td>
        <img src="@Url.Content(item.CImage1)" width="200" height="200" />
    </td>
    <td>
        <img src="@Url.Content(item.CImage2)" width="200" height="200" />
    </td>
    <td>
        <img src="@Url.Content(item.CImage3)" width="200" height="200" />
    </td>
    <td>
        <img src="@Url.Content(item.CImage4)" width="200" height="200" />
    </td>
    <td>

        @Html.ActionLink("Edit", "Edit", new { id = item.CID }) |
        @Html.ActionLink("Details", "Details", new { id = item.CID }) |
        @Html.ActionLink("Delete", "Delete", new { id = item.CID })

    </td>
</tr>
}

</table>

Views/Clinics/Login.cshtml
@model GetHair_Egypt.Models.Clinic

@{
    ViewBag.Title = "Login";
}

<h2>Login</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Clinic</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })           

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.PasswordFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

       

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Login" class="btn btn-default" />
                <br/>
                @ViewBag.error
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}